"""Add face_embedding and DispatchUnit lat/lng

Revision ID: 9836630639d6
Revises: 293d531ef43c
Create Date: 2026-06-08 18:40:46.815608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9836630639d6'
down_revision: Union[str, Sequence[str], None] = '293d531ef43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_units', sa.Column('last_known_lat', sa.Float(), nullable=True))
    op.add_column('dispatch_units', sa.Column('last_known_lng', sa.Float(), nullable=True))
    op.add_column('missing_persons', sa.Column('face_embedding', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missing_persons', 'face_embedding')
    op.drop_column('dispatch_units', 'last_known_lng')
    op.drop_column('dispatch_units', 'last_known_lat')
    # ### end Alembic commands ###
