"""Add SystemSettings

Revision ID: d94797cbcd00
Revises: 9836630639d6
Create Date: 2026-06-22 10:32:46.728007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94797cbcd00'
down_revision: Union[str, Sequence[str], None] = '9836630639d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('processing_engine', sa.String(length=20), nullable=False),
    sa.Column('detection_threshold', sa.Float(), nullable=False),
    sa.Column('face_extraction_enabled', sa.Boolean(), nullable=False),
    sa.Column('sound_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
